var path = require('path')
var custom = require(path.join(process.cwd(), 'scenarios.conf'))

var argv = require('yargs').argv
var mode = argv.mode

var baseConf = {
  command: {
    base: 'node',
    args: ['server.js']
  },
  targetServerPort: 3000,
  proxiedApiUrl: 'http://pokeapi.co/',
  frontendProxyPort: 3001,
  backendProxyPort: 3002,
  backendDir: 'backend_tapes',
  frontendDir: 'frontend_tapes',
  frontendTestingDir: 'temporal_testing_fronted_tapes',
  mode: mode,
  isTesting: mode === 'test'
}

var proxyConf = {
  feOpts: {
    baseDir: path.join(process.cwd(), baseConf.isTesting ? baseConf.frontendTestingDir : baseConf.frontendDir),
    dirname: 'foo'
  },
  beOpts: {
    dirname: path.join(process.cwd(), baseConf.backendDir)
  }
}

var testerConf = {
  doNotCompare: [
    'autogenerated'
  ]
}

module.exports = Object.assign(baseConf,
    Object.assign(proxyConf,
    Object.assign(testerConf, custom)))
