var http = require('http')
var request = require('request-promise')

http.createServer(function (req, res) {
  request('http://localhost:3002/api/v2/pokemon/7/')
    .then(function (body) {
      res.writeHead(200, {'Content-Type': 'text/json'})
      var jsonBody = JSON.parse(body)
      jsonBody.testingAttrChange = 'qwer'
      jsonBody.autogenerated = {}
      jsonBody.autogenerated.id = Date.now()
      res.end(JSON.stringify(jsonBody, null, 4))
    })
}).listen(3000, function () {
  console.log('the server has started')
})
